name: NSE BULK DMA

on:
  workflow_dispatch:

jobs:

  sync:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Script
        env:
          GOOGLE_CREDS_SECRET: ${{ secrets.GOOGLE_CREDS_SECRET }}
        run: |
          python pipeline_sync.py
